language:
  - minimal

services:
  - docker
env:
  matrix:
    - RAKUDO-VERSION=2019.11
    - RAKUDO-VERSION=daily
    # Add here with recent versions in future
 

script: |
  docker run -it -v $(pwd):/tmp -w /tmp sumankhanal/rakudo:${RAKUDO-VERSION} /bin/sh -c '
  apt-get update
  apt-get install -y build-essential wget libzmq3-dev ca-certificates
  prove6 --lib t/'