language: perl6
perl6:
  - latest
before_install:
  - wget https://github.com/zeromq/libzmq/releases/download/v4.2.2/zeromq-4.2.2.tar.gz
  - tar -xzvf zeromq-4.2.2.tar.gz
  - pushd zeromq-4.2.2 && ./configure --prefix=/usr && make && sudo make install && popd
install:
  - rakudobrew build zef
  - zef install --depsonly .

