language:
  - minimal

services:
  - docker

env:
  matrix:
    - RAKUDO_VERSION=daily
    - RAKUDO_VERSION=2019.11
    
 

script: |
  docker run -it -v $(pwd):/home -w /home sumankhanal/rakudo:${RAKUDO_VERSION} /bin/sh -c "
  apt-get update && 
  apt-get install -y libzmq3-dev &&
  zef install --depsonly . &&
  prove6 --lib t/"

